<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Batches.Generic\Batches.Generic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configurations\Files\" />
    <Folder Include="Configurations\Objects\" />
    <Folder Include="Implementations\" />
  </ItemGroup>

</Project>
