<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
	<RootNamespace>DataProviders.YahooFincnaceProviders</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core\Technicals.csproj" />
    <ProjectReference Include="..\..\Core\Http\Http.csproj" />
    <ProjectReference Include="..\..\Models\Models\Models.csproj" />
    <ProjectReference Include="..\..\Models\TechnicalModels\TechnicalModels.csproj" />
    <ProjectReference Include="..\GenericProvider\GenericProvider.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configuration\yahoo_finance_settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
